# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Train

on:
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
  
    - name: Login to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: |
        export TAG=$(git rev-parse --short HEAD)
        docker build . -t CICD_asgn:$TAG

    - name: Push Docker image
      run: |
        docker push CICD_asgn:$TAG
